<?php

namespace Delegation\Classes;

use Delegation\Classes\CourierServiceAbstract;

class CarCourierService extends CourierServiceAbstract
{
    public function deliver()
    {
        return parent::deliver(); // TODO: Change the autogenerated stub
    }
}